name: Trigger Artifact Release

on:
  workflow_call:

permissions:
  contents: read
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Trigger workflow
        run: git tag --list "v*" | xargs -I {} -n1 gh workflow run artifact-release.yml -f tag={}
        env:
          GH_TOKEN: ${{ github.token }}
